# Covid-19

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', 500)

df = pd.read_csv('owid-covid-data.csv')
df.shape

(75757, 59)

In [13]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,7.451500e+04,74513.000000,73512.000000,6.524600e+04,65404.000000,73512.000000,74109.000000,74107.000000,73111.000000,64853.000000,...,68938.000000,47029.000000,69557.000000,70454.000000,54650.000000,53899.000000,34922.000000,63637.000000,71982.00000,69498.000000
mean,6.690480e+05,5201.533612,5206.901749,1.968004e+04,132.387163,116.562153,7960.645516,67.655724,67.449308,186.112761,...,19148.031930,13.290504,257.303348,7.800413,10.547703,32.648715,50.991714,3.035411,73.14801,0.727777
std,4.693180e+06,32405.796111,32067.778369,1.153478e+05,724.136743,661.632138,15627.377878,169.557033,142.715432,330.555997,...,19746.669962,19.925890,118.505755,3.944585,10.409438,13.467121,31.767269,2.466880,7.55209,0.150156
min,1.000000e+00,-74347.000000,-6223.000000,1.000000e+00,-1918.000000,-232.143000,0.001000,-2153.437000,-276.825000,0.001000,...,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.28000,0.394000
25%,7.320000e+02,2.000000,6.000000,3.900000e+01,0.000000,0.000000,153.951000,0.145000,1.019000,5.754000,...,4466.507000,0.500000,167.295000,5.290000,1.900000,21.600000,20.859000,1.300000,67.88000,0.602000
50%,8.306000e+03,61.000000,73.286000,2.570000e+02,2.000000,1.000000,1107.609000,6.515000,8.669000,32.086000,...,12951.839000,2.000000,242.648000,7.110000,6.300000,31.400000,49.839000,2.400000,74.53000,0.748000
75%,8.951150e+04,682.000000,706.571000,2.451000e+03,16.000000,12.286000,7429.723000,58.290500,65.472000,198.091000,...,27216.445000,21.200000,329.635000,10.080000,19.300000,41.100000,83.241000,4.000000,78.73000,0.848000
max,1.217865e+08,880902.000000,739564.429000,2.691035e+06,17895.000000,14424.000000,147453.569000,8652.658000,2648.773000,2298.309000,...,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.75000,0.957000